# Generated by Django 2.0.7 on 2020-10-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201015_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=' thumbDefault.png', upload_to='Thumbnails'),
        ),
    ]
