# Generated by Django 2.0.7 on 2020-10-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='thumbDefault.png', upload_to='Thumbnails'),
        ),
    ]
