# Generated by Django 2.0.7 on 2020-10-26 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201020_0421'),
        ('blog', '0005_auto_20201018_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_to_be_liked', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('profile_that_liked', models.ManyToManyField(to='users.Profile')),
            ],
        ),
    ]
