# Generated by Django 2.0.7 on 2020-10-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='number_of_like',
            field=models.IntegerField(default=0),
        ),
    ]
