# Generated by Django 2.0.7 on 2020-10-27 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201020_0421'),
        ('blog', '0007_likes_number_of_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='likes',
            name='Post_to_be_liked',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='number_of_like',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='profile_that_liked',
        ),
        migrations.AddField(
            model_name='likes',
            name='Status',
            field=models.CharField(choices=[('unlike', 'unlike'), ('like', 'like')], default='unlike', max_length=6),
        ),
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='Liked',
            field=models.ManyToManyField(default=None, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
