# Generated by Django 2.0.7 on 2020-10-27 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201027_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='Status',
            field=models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], max_length=6),
        ),
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
