# Generated by Django 2.0.7 on 2020-10-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201027_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='Status',
            field=models.CharField(choices=[('unlike', 'unlike'), ('like', 'like')], max_length=6),
        ),
    ]
