# Generated by Django 2.0.7 on 2020-10-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201027_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='Status',
            field=models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='Thumbnails'),
        ),
    ]
