# Generated by Django 2.0.7 on 2020-10-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201016_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Fname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Lname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
