# Generated by Django 2.0.7 on 2020-10-18 08:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201016_1537'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='relationship',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
