# Generated by Django 2.0.7 on 2020-10-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201018_0823'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='relationship',
            managers=[
            ],
        ),
    ]
