# Generated by Django 2.0.7 on 2021-02-14 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_auto_20210214_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='Applicants', to='users.Profile'),
        ),
    ]
